### ISSUE TITLE
Klein scherm niet responsief

### ISSUE THREAD

**Issue by KobeDaniels** [Wouter127/E2-Metavision-Frontend#116]
http://wijn-angular.northeurope.cloudapp.azure.com/weerstation/2/dashboard
![image](https://user-images.githubusercontent.com/57659711/153824483-f92f8246-c53e-4002-8f57-30e6a913330e.png)

**Comment by Wouter127** [comment]
#118 
![image](https://user-images.githubusercontent.com/57892609/153867199-1b4129cb-c9c7-47da-a1df-acf17ffcbf68.png)
