### ISSUE TITLE
Nieuw weerstation heeft geen metingen maar...

### ISSUE THREAD

**Issue by JulianKoppens** [Wouter127/E2-Metavision-Frontend#39]
Als ik een nieuw weerstation maak + toevoeg aan een organisatie heeft dit geen metingen. Als ik naar het dashboard ga zijn hier wel grafieken met data in

**Comment by Wouter127** [comment]
kwam wrs omdat de data toen nog hard coded was, nu zie ik lege tabellen met 'geen data om weer te geven'
